// Catalog de produse pe magazin. Prețurile sunt ESTIMATIVE (RON) și pot fi editate din site.
// unit: g | ml | buc. pack = cantitatea dintr-un ambalaj.
const SECTIONS = {
  produce: "🥦 Legume & Fructe",
  meat: "🍗 Carne & Pește",
  dairy: "🧀 Lactate & Ouă",
  pantry: "🥫 Cămară",
  frozen: "🧊 Congelate",
  bakery: "🍞 Panificație",
  misc: "🧻 Diverse",
};

// id -> { name, section, unit, lidl: {product, pack, price}, kaufland: {...} }
const PRODUCTS = {
  piept_pui:   { name: "Piept de pui", section: "meat", unit: "g",
    lidl: { product: "Piept de pui file, 1 kg", pack: 1000, price: 29.99 },
    kaufland: { product: "K-Classic piept de pui, 1 kg", pack: 1000, price: 28.90 } },
  pulpe_pui:   { name: "Pulpe de pui dezosate", section: "meat", unit: "g",
    lidl: { product: "Pulpe pui dezosate, 800 g", pack: 800, price: 21.99 },
    kaufland: { product: "Pulpe superioare dezosate, 1 kg", pack: 1000, price: 24.90 } },
  carne_tocata:{ name: "Carne tocată vită", section: "meat", unit: "g",
    lidl: { product: "Carne tocată vită, 500 g", pack: 500, price: 22.99 },
    kaufland: { product: "Carne tocată vită, 500 g", pack: 500, price: 21.90 } },
  curcan:      { name: "Piept de curcan", section: "meat", unit: "g",
    lidl: { product: "Piept curcan, 500 g", pack: 500, price: 21.49 },
    kaufland: { product: "Piept curcan, 500 g", pack: 500, price: 20.90 } },
  somon:       { name: "File somon", section: "frozen", unit: "g",
    lidl: { product: "Ocean Sea file somon congelat, 500 g", pack: 500, price: 34.99 },
    kaufland: { product: "File somon congelat, 500 g", pack: 500, price: 36.90 } },
  ton:         { name: "Ton conservă", section: "pantry", unit: "g",
    lidl: { product: "Nixe ton în suc propriu, 3×80 g", pack: 240, price: 15.99 },
    kaufland: { product: "K-Classic ton bucăți, 3×80 g", pack: 240, price: 14.90 } },
  oua:         { name: "Ouă", section: "dairy", unit: "buc",
    lidl: { product: "Ouă M, 10 buc", pack: 10, price: 9.99 },
    kaufland: { product: "Ouă M, 10 buc", pack: 10, price: 9.79 } },
  iaurt_grec:  { name: "Iaurt grecesc", section: "dairy", unit: "g",
    lidl: { product: "Pilos iaurt grecesc 10%, 400 g", pack: 400, price: 7.49 },
    kaufland: { product: "K-Classic iaurt grecesc, 400 g", pack: 400, price: 7.29 } },
  branza_vaci: { name: "Brânză de vaci", section: "dairy", unit: "g",
    lidl: { product: "Pilos brânză de vaci, 500 g", pack: 500, price: 9.99 },
    kaufland: { product: "Brânză de vaci, 500 g", pack: 500, price: 9.90 } },
  mozzarella:  { name: "Mozzarella", section: "dairy", unit: "g",
    lidl: { product: "Lovilio mozzarella, 125 g", pack: 125, price: 3.99 },
    kaufland: { product: "K-Classic mozzarella, 125 g", pack: 125, price: 3.89 } },
  feta:        { name: "Telemea / Feta", section: "dairy", unit: "g",
    lidl: { product: "Eridanous feta, 200 g", pack: 200, price: 8.99 },
    kaufland: { product: "Telemea de vacă, 400 g", pack: 400, price: 12.90 } },
  lapte:       { name: "Lapte", section: "dairy", unit: "ml",
    lidl: { product: "Pilos lapte 1.5%, 1 L", pack: 1000, price: 6.49 },
    kaufland: { product: "K-Classic lapte 1.5%, 1 L", pack: 1000, price: 6.29 } },
  parmezan:    { name: "Parmezan ras", section: "dairy", unit: "g",
    lidl: { product: "Lovilio Grana Padano ras, 100 g", pack: 100, price: 7.99 },
    kaufland: { product: "Parmezan ras, 100 g", pack: 100, price: 8.49 } },
  orez:        { name: "Orez", section: "pantry", unit: "g",
    lidl: { product: "Golden Sun orez basmati, 1 kg", pack: 1000, price: 9.99 },
    kaufland: { product: "K-Classic orez basmati, 1 kg", pack: 1000, price: 9.49 } },
  paste:       { name: "Paste", section: "pantry", unit: "g",
    lidl: { product: "Combino penne, 500 g", pack: 500, price: 3.49 },
    kaufland: { product: "K-Classic penne, 500 g", pack: 500, price: 3.29 } },
  ovaz:        { name: "Fulgi de ovăz", section: "pantry", unit: "g",
    lidl: { product: "Crownfield fulgi ovăz, 500 g", pack: 500, price: 4.49 },
    kaufland: { product: "K-Classic fulgi ovăz, 500 g", pack: 500, price: 4.29 } },
  linte:       { name: "Linte roșie", section: "pantry", unit: "g",
    lidl: { product: "Linte roșie, 500 g", pack: 500, price: 6.99 },
    kaufland: { product: "Linte roșie, 500 g", pack: 500, price: 7.49 } },
  naut:        { name: "Năut conservă", section: "pantry", unit: "g",
    lidl: { product: "Freshona năut, 400 g", pack: 400, price: 3.99 },
    kaufland: { product: "K-Classic năut, 400 g", pack: 400, price: 3.79 } },
  fasole:      { name: "Fasole roșie conservă", section: "pantry", unit: "g",
    lidl: { product: "Freshona fasole roșie, 400 g", pack: 400, price: 3.79 },
    kaufland: { product: "K-Classic fasole roșie, 400 g", pack: 400, price: 3.59 } },
  rosii_conserva:{ name: "Roșii tăiate conservă", section: "pantry", unit: "g",
    lidl: { product: "Baresa roșii tăiate, 400 g", pack: 400, price: 3.49 },
    kaufland: { product: "K-Classic roșii tăiate, 400 g", pack: 400, price: 3.29 } },
  lapte_cocos: { name: "Lapte de cocos", section: "pantry", unit: "ml",
    lidl: { product: "Vitasia lapte cocos, 400 ml", pack: 400, price: 6.99 },
    kaufland: { product: "Lapte de cocos, 400 ml", pack: 400, price: 7.49 } },
  wrap:        { name: "Lipii / tortilla", section: "bakery", unit: "buc",
    lidl: { product: "Tortilla grâu, 6 buc", pack: 6, price: 6.99 },
    kaufland: { product: "K-Classic tortilla, 6 buc", pack: 6, price: 6.49 } },
  paine:       { name: "Pâine integrală", section: "bakery", unit: "g",
    lidl: { product: "Pâine integrală feliată, 500 g", pack: 500, price: 5.99 },
    kaufland: { product: "Pâine integrală, 500 g", pack: 500, price: 5.79 } },
  cartofi:     { name: "Cartofi", section: "produce", unit: "g",
    lidl: { product: "Cartofi, plasă 2 kg", pack: 2000, price: 7.99 },
    kaufland: { product: "Cartofi, plasă 2 kg", pack: 2000, price: 7.49 } },
  cartofi_dulci:{ name: "Cartofi dulci", section: "produce", unit: "g",
    lidl: { product: "Cartofi dulci, 1 kg", pack: 1000, price: 9.99 },
    kaufland: { product: "Cartofi dulci, 1 kg", pack: 1000, price: 10.90 } },
  broccoli:    { name: "Broccoli", section: "produce", unit: "g",
    lidl: { product: "Broccoli, 500 g", pack: 500, price: 6.99 },
    kaufland: { product: "Broccoli, 500 g", pack: 500, price: 6.49 } },
  ardei:       { name: "Ardei gras", section: "produce", unit: "buc",
    lidl: { product: "Ardei tricolor, 3 buc", pack: 3, price: 7.99 },
    kaufland: { product: "Ardei mix, 3 buc", pack: 3, price: 7.49 } },
  ceapa:       { name: "Ceapă", section: "produce", unit: "buc",
    lidl: { product: "Ceapă galbenă, 1 kg (~8 buc)", pack: 8, price: 3.49 },
    kaufland: { product: "Ceapă galbenă, 1 kg (~8 buc)", pack: 8, price: 3.29 } },
  usturoi:     { name: "Usturoi", section: "produce", unit: "buc",
    lidl: { product: "Usturoi, 3 căpățâni (~30 căței)", pack: 30, price: 4.99 },
    kaufland: { product: "Usturoi, 250 g (~30 căței)", pack: 30, price: 4.79 } },
  rosii:       { name: "Roșii", section: "produce", unit: "g",
    lidl: { product: "Roșii, 1 kg", pack: 1000, price: 8.99 },
    kaufland: { product: "Roșii, 1 kg", pack: 1000, price: 8.49 } },
  castraveti:  { name: "Castraveți", section: "produce", unit: "buc",
    lidl: { product: "Castravete, 1 buc", pack: 1, price: 2.49 },
    kaufland: { product: "Castravete, 1 buc", pack: 1, price: 2.29 } },
  spanac:      { name: "Spanac baby", section: "produce", unit: "g",
    lidl: { product: "Spanac baby, 200 g", pack: 200, price: 5.99 },
    kaufland: { product: "Spanac baby, 150 g", pack: 150, price: 5.49 } },
  salata:      { name: "Salată verde mix", section: "produce", unit: "g",
    lidl: { product: "Mix salată, 200 g", pack: 200, price: 5.49 },
    kaufland: { product: "Mix salată, 200 g", pack: 200, price: 5.29 } },
  dovlecei:    { name: "Dovlecei", section: "produce", unit: "g",
    lidl: { product: "Dovlecei, 500 g", pack: 500, price: 5.49 },
    kaufland: { product: "Dovlecei, 500 g", pack: 500, price: 5.29 } },
  morcovi:     { name: "Morcovi", section: "produce", unit: "g",
    lidl: { product: "Morcovi, 1 kg", pack: 1000, price: 3.99 },
    kaufland: { product: "Morcovi, 1 kg", pack: 1000, price: 3.79 } },
  banane:      { name: "Banane", section: "produce", unit: "buc",
    lidl: { product: "Banane, ~6 buc", pack: 6, price: 6.99 },
    kaufland: { product: "Banane, ~6 buc", pack: 6, price: 6.79 } },
  fructe_padure:{ name: "Fructe de pădure", section: "frozen", unit: "g",
    lidl: { product: "Freshona fructe pădure congelate, 750 g", pack: 750, price: 13.99 },
    kaufland: { product: "Fructe de pădure congelate, 450 g", pack: 450, price: 9.90 } },
  avocado:     { name: "Avocado", section: "produce", unit: "buc",
    lidl: { product: "Avocado, 2 buc", pack: 2, price: 8.99 },
    kaufland: { product: "Avocado, 1 buc", pack: 1, price: 4.49 } },
  lamaie:      { name: "Lămâie", section: "produce", unit: "buc",
    lidl: { product: "Lămâi, 500 g (~4 buc)", pack: 4, price: 5.49 },
    kaufland: { product: "Lămâi, 500 g (~4 buc)", pack: 4, price: 5.29 } },
  mazare:      { name: "Mazăre congelată", section: "frozen", unit: "g",
    lidl: { product: "Freshona mazăre, 750 g", pack: 750, price: 7.99 },
    kaufland: { product: "K-Classic mazăre, 750 g", pack: 750, price: 7.49 } },
  legume_wok:  { name: "Mix legume wok", section: "frozen", unit: "g",
    lidl: { product: "Freshona mix wok, 750 g", pack: 750, price: 9.99 },
    kaufland: { product: "K-Classic mix asiatic, 750 g", pack: 750, price: 9.49 } },
  unt_arahide: { name: "Unt de arahide", section: "pantry", unit: "g",
    lidl: { product: "Alesto unt arahide, 350 g", pack: 350, price: 9.99 },
    kaufland: { product: "Unt de arahide, 350 g", pack: 350, price: 10.49 } },
  sos_soia:    { name: "Sos de soia", section: "pantry", unit: "ml",
    lidl: { product: "Vitasia sos soia, 250 ml", pack: 250, price: 5.49 },
    kaufland: { product: "Sos soia, 250 ml", pack: 250, price: 5.79 } },
  miere:       { name: "Miere", section: "pantry", unit: "g",
    lidl: { product: "Miere poliflora, 400 g", pack: 400, price: 14.99 },
    kaufland: { product: "Miere poliflora, 400 g", pack: 400, price: 14.49 } },
  pesto:       { name: "Pesto", section: "pantry", unit: "g",
    lidl: { product: "Baresa pesto genovese, 190 g", pack: 190, price: 7.99 },
    kaufland: { product: "Pesto genovese, 190 g", pack: 190, price: 8.49 } },
  pungi:       { name: "Caserole meal prep", section: "misc", unit: "buc",
    lidl: { product: "Caserole plastic cu capac, 10 buc", pack: 10, price: 12.99 },
    kaufland: { product: "Caserole cu capac, 10 buc", pack: 10, price: 11.90 } },
};

// Condimente de bază pe care le presupunem acasă (nu intră în listă dacă bifezi „am acasă”)
const STAPLES = ["Sare", "Piper", "Ulei de măsline", "Boia", "Usturoi praf", "Chimion", "Oregano", "Curry"];

// Ingrediente PER PORȚIE. tags: pentru filtrare (diete, alergeni).
// diet: lista de diete compatibile. allergens: gluten, lactoza, oua, peste, nuci
const RECIPES = [
  { id: "pui_orez_broccoli", name: "Bol de pui cu orez și broccoli", type: "main", time: 30, kcal: 560, p: 48, c: 60, f: 12,
    diet: ["echilibrat", "high-protein"], allergens: [],
    ing: { piept_pui: 170, orez: 75, broccoli: 150, usturoi: 1 },
    steps: "Gătește orezul. Taie puiul cuburi, condimentează cu boia + usturoi și rumenește 8–10 min. Broccoli la abur 5 min. Împarte în caserole." },
  { id: "chili", name: "Chili con carne", type: "main", time: 45, kcal: 610, p: 42, c: 55, f: 22,
    diet: ["echilibrat", "high-protein"], allergens: [],
    ing: { carne_tocata: 150, fasole: 120, rosii_conserva: 150, ceapa: 0.5, ardei: 0.5, orez: 60 },
    steps: "Călește ceapa și ardeiul, adaugă carnea, rumenește. Pune roșiile, fasolea, chimion, boia. Fierbe 25 min. Servește cu orez." },
  { id: "curry_naut", name: "Curry de năut cu spanac", type: "main", time: 30, kcal: 520, p: 18, c: 62, f: 20,
    diet: ["echilibrat", "vegetarian", "vegan"], allergens: [],
    ing: { naut: 200, lapte_cocos: 100, spanac: 60, ceapa: 0.5, rosii_conserva: 100, orez: 60 },
    steps: "Călește ceapa, adaugă curry, roșiile și laptele de cocos. Pune năutul, fierbe 15 min, la final spanacul. Servește cu orez." },
  { id: "somon_cartofi_dulci", name: "Somon la cuptor cu cartofi dulci", type: "main", time: 35, kcal: 590, p: 36, c: 50, f: 26,
    diet: ["echilibrat", "high-protein", "mediteranean"], allergens: ["peste"],
    ing: { somon: 150, cartofi_dulci: 220, broccoli: 120, lamaie: 0.25 },
    steps: "Cartofii dulci cuburi la 200°C 20 min. Adaugă somonul și broccoli, încă 12–15 min. Stoarce lămâie deasupra." },
  { id: "paste_pesto_pui", name: "Paste cu pesto și pui", type: "main", time: 25, kcal: 650, p: 45, c: 70, f: 20,
    diet: ["echilibrat", "high-protein"], allergens: ["gluten", "lactoza", "nuci"],
    ing: { paste: 90, piept_pui: 130, pesto: 30, rosii: 80, parmezan: 10 },
    steps: "Fierbe pastele. Rumenește puiul fâșii. Amestecă cu pesto, roșii tăiate și parmezan." },
  { id: "stir_fry_curcan", name: "Stir-fry de curcan cu legume", type: "main", time: 20, kcal: 480, p: 42, c: 50, f: 10,
    diet: ["echilibrat", "high-protein", "low-carb"], allergens: [],
    ing: { curcan: 150, legume_wok: 200, sos_soia: 20, orez: 55, usturoi: 1 },
    steps: "Curcanul fâșii la foc mare 5 min, adaugă legumele, usturoiul și sosul de soia, încă 6 min. Cu orez." },
  { id: "supa_linte", name: "Supă cremă de linte", type: "main", time: 35, kcal: 420, p: 22, c: 60, f: 8,
    diet: ["echilibrat", "vegetarian", "vegan"], allergens: [],
    ing: { linte: 80, morcovi: 100, ceapa: 0.5, rosii_conserva: 100, usturoi: 1 },
    steps: "Călește ceapa, morcovii, usturoiul. Adaugă lintea, roșiile și 600 ml apă/porție dublă. Fierbe 20 min, pasează." },
  { id: "pui_cartofi_cuptor", name: "Pulpe de pui cu cartofi la cuptor", type: "main", time: 50, kcal: 640, p: 40, c: 52, f: 28,
    diet: ["echilibrat"], allergens: [],
    ing: { pulpe_pui: 180, cartofi: 250, morcovi: 80, ceapa: 0.5 },
    steps: "Totul în tavă cu ulei, boia, sare, piper. 200°C, 40–45 min, întoarce la jumătate." },
  { id: "low_carb_dovlecei", name: "Pui cu dovlecei și feta (low-carb)", type: "main", time: 25, kcal: 430, p: 46, c: 12, f: 22,
    diet: ["low-carb", "keto", "high-protein", "mediteranean"], allergens: ["lactoza"],
    ing: { piept_pui: 170, dovlecei: 200, feta: 40, rosii: 80 },
    steps: "Rumenește puiul, adaugă dovlecei felii și roșiile, 8 min. Sfărâmă feta deasupra." },
  { id: "wrap_ton", name: "Wrap cu ton și legume", type: "main", time: 10, kcal: 470, p: 34, c: 45, f: 16,
    diet: ["echilibrat", "high-protein"], allergens: ["gluten", "peste", "lactoza"],
    ing: { wrap: 1.5, ton: 80, iaurt_grec: 30, salata: 30, castraveti: 0.3, rosii: 60 },
    steps: "Amestecă tonul cu iaurtul. Pune pe lipie cu salata, castraveții și roșiile, rulează. Ideal la pachet." },
  { id: "bol_med", name: "Bol mediteranean cu năut și feta", type: "main", time: 15, kcal: 510, p: 20, c: 48, f: 26,
    diet: ["vegetarian", "mediteranean", "echilibrat"], allergens: ["lactoza"],
    ing: { naut: 150, castraveti: 0.5, rosii: 120, feta: 50, salata: 40, lamaie: 0.25 },
    steps: "Combină totul, stropește cu ulei de măsline, lămâie și oregano. Fără gătit!" },
  { id: "omleta_legume", name: "Frittata cu legume (la cuptor)", type: "breakfast", time: 25, kcal: 340, p: 24, c: 8, f: 23,
    diet: ["vegetarian", "low-carb", "keto", "echilibrat"], allergens: ["oua", "lactoza"],
    ing: { oua: 3, ardei: 0.3, spanac: 30, mozzarella: 30 },
    steps: "Bate ouăle, adaugă legumele și mozzarella. Tavă la 180°C 20 min. Se taie felii pentru 3–4 zile." },
  { id: "overnight_oats", name: "Overnight oats cu fructe de pădure", type: "breakfast", time: 5, kcal: 380, p: 20, c: 55, f: 9,
    diet: ["vegetarian", "echilibrat"], allergens: ["gluten", "lactoza"],
    ing: { ovaz: 50, iaurt_grec: 100, lapte: 80, fructe_padure: 70, miere: 10 },
    steps: "Amestecă ovăzul, iaurtul și laptele în borcan, fructele deasupra. Frigider peste noapte." },
  { id: "tost_avocado", name: "Toast cu avocado și ou", type: "breakfast", time: 10, kcal: 400, p: 17, c: 32, f: 23,
    diet: ["vegetarian", "echilibrat"], allergens: ["gluten", "oua"],
    ing: { paine: 70, avocado: 0.5, oua: 1.5, lamaie: 0.1 },
    steps: "Prăjește pâinea, zdrobește avocado cu lămâie și sare, adaugă oul fiert/ochi." },
  { id: "clatite_banane", name: "Clătite proteice cu banană", type: "breakfast", time: 15, kcal: 360, p: 24, c: 42, f: 10,
    diet: ["vegetarian", "high-protein"], allergens: ["oua", "lactoza", "gluten"],
    ing: { banane: 1, oua: 2, ovaz: 30, branza_vaci: 60 },
    steps: "Mixează totul, coace clătite mici în tigaie unsă 2 min/parte." },
  { id: "branza_fructe", name: "Brânză de vaci cu fructe și miere", type: "snack", time: 3, kcal: 230, p: 22, c: 22, f: 5,
    diet: ["vegetarian", "high-protein"], allergens: ["lactoza"],
    ing: { branza_vaci: 150, fructe_padure: 60, miere: 8 },
    steps: "Pune într-un bol. Gata." },
  { id: "banana_unt", name: "Banană cu unt de arahide", type: "snack", time: 2, kcal: 250, p: 7, c: 30, f: 12,
    diet: ["vegetarian", "vegan", "echilibrat"], allergens: ["nuci"],
    ing: { banane: 1, unt_arahide: 20 },
    steps: "Feliază banana, ungi cu unt de arahide." },
  { id: "oua_fierte", name: "Ouă fierte + castravete", type: "snack", time: 10, kcal: 170, p: 13, c: 3, f: 11,
    diet: ["vegetarian", "low-carb", "keto"], allergens: ["oua"],
    ing: { oua: 2, castraveti: 0.3 },
    steps: "Fierbe ouăle 9 min, răcește în apă rece. Rezistă 5 zile în frigider." },
];
